---
- name: Criar usuário do Zabbix
  community.postgresql.postgresql_user:
    name: "{{ zabbix_db_user }}"
    password: "{{ zabbix_db_password }}"
    encrypted: true
    role_attr_flags: CREATEDB
    login_user: postgres
    login_unix_socket: /var/run/postgresql

- name: Criar banco de dados Zabbix
  become: true
  community.postgresql.postgresql_db:
    name: "{{ zabbix_db_name }}"
    owner: "{{ zabbix_db_user }}"
    encoding: UTF8
    lc_collate: en_US.UTF-8
    lc_ctype: en_US.UTF-8
    template: template0

- name: Ativar extensão TimescaleDB
  become: true
  community.postgresql.postgresql_ext:
    name: timescaledb
    db: "{{ zabbix_db_name }}"
    state: present

- name: Permitir acesso ao banco Zabbix via md5
  become: true
  community.postgresql.postgresql_pg_hba:
    dest: /etc/postgresql/16/main/pg_hba.conf
    contype: host
    users: "{{ zabbix_db_user }}"
    source: 0.0.0.0/0
    databases: "{{ zabbix_db_name }}"
    method: md5

- name: Configurar postgresql.conf para aceitar conexões externas
  become: true
  community.postgresql.postgresql_set:
    name: listen_addresses
    value: "'*'"
    setting: postgresql.conf
    state: present
    reload: yes
    login_user: postgres
    login_unix_socket: /var/run/postgresql
  notify: Restart PostgreSQL

- name: Carregar schema do Zabbix - server.sql.gz
  become: true
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "/usr/share/zabbix-sql-scripts/postgresql/server.sql.gz"
    login_user: postgres
    login_unix_socket: /var/run/postgresql

- name: Carregar schema do Zabbix - images.sql.gz
  become: true
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "/usr/share/zabbix-sql-scripts/postgresql/images.sql.gz"
    login_user: postgres
    login_unix_socket: /var/run/postgresql

- name: Carregar schema do Zabbix - data.sql.gz
  become: true
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "/usr/share/zabbix-sql-scripts/postgresql/data.sql.gz"
    login_user: postgres
    login_unix_socket: /var/run/postgresql

- name: Carregar schema específico do TimescaleDB
  become: true
  community.postgresql.postgresql_script:
    db: "{{ zabbix_db_name }}"
    path: "/usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql"
    login_user: postgres
    login_unix_socket: /var/run/postgresql
