---
- name: Criar usuário do Zabbix
  shell: |
    sudo -u postgres psql -c "DO \$\$ BEGIN
      IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ zabbix_db_user }}'
      ) THEN
        CREATE ROLE {{ zabbix_db_user }} WITH LOGIN PASSWORD '{{ zabbix_db_password }}' CREATEDB;
      END IF;
    END \$\$;"

- name: Criar banco de dados Zabbix
  shell: |
    sudo -u postgres psql -c "CREATE DATABASE {{ zabbix_db_name }}
      WITH OWNER = '{{ zabbix_db_user }}'
      ENCODING = 'UTF8'
      LC_COLLATE = 'en_US.UTF-8'
      LC_CTYPE = 'en_US.UTF-8'
      TEMPLATE = template0;"

- name: Criar usuário de monitoramento ({{ zabbix_monitor_user }})
  shell: |
    sudo -u postgres psql -c "DO \$\$ BEGIN
      IF NOT EXISTS (
        SELECT FROM pg_roles WHERE rolname = '{{ zabbix_monitor_user }}'
      ) THEN
        CREATE ROLE {{ zabbix_monitor_user }} WITH LOGIN PASSWORD '{{ zabbix_monitor_password }}';
        GRANT pg_monitor TO {{ zabbix_monitor_user }};
      END IF;
    END \$\$;"

- name: Permitir acesso ao PostgreSQL para {{ zabbix_monitor_user }}
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    insertafter: EOF
    line: "host    all    {{ zabbix_monitor_user }}    127.0.0.1/32    md5"
    state: present

- name: Carregar schema do Zabbix com usuário zabbix (server.sql.gz)
  shell: |
    zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql -h 127.0.0.1 -U {{ zabbix_db_user }} -d {{ zabbix_db_name }}
  environment:
    PGPASSWORD: "{{ zabbix_db_password }}"

- name: Carregar schema específico do TimescaleDB com usuário zabbix
  shell: |
    psql -h 127.0.0.1 -U {{ zabbix_db_user }} -d {{ zabbix_db_name }} -f /usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql
  environment:
    PGPASSWORD: "{{ zabbix_db_password }}"

- name: Ativar extensão TimescaleDB
  shell: sudo -u postgres psql -d {{ zabbix_db_name }} -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"
  notify: Restart PostgreSQL
