---
- name: Criar usuário do Zabbix
  shell: |
    sudo -u postgres psql -c "DO \$\$ BEGIN
      IF NOT EXISTS (
        SELECT FROM pg_catalog.pg_roles WHERE rolname = '{{ zabbix_db_user }}'
      ) THEN
        CREATE ROLE {{ zabbix_db_user }} WITH LOGIN PASSWORD '{{ zabbix_db_password }}' CREATEDB;
      END IF;
    END \$\$;"

- name: Criar banco de dados Zabbix
  shell: |
    sudo -u postgres psql -c "CREATE DATABASE {{ zabbix_db_name }}
      WITH OWNER = '{{ zabbix_db_user }}'
      ENCODING = 'UTF8'
      LC_COLLATE = 'en_US.UTF-8'
      LC_CTYPE = 'en_US.UTF-8'
      TEMPLATE = template0;"

- name: Carregar schema do Zabbix - server.sql.gz
  shell: "zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u postgres psql {{ zabbix_db_name }}"

- name: Carregar schema específico do TimescaleDB
  shell: "sudo -u postgres psql {{ zabbix_db_name }} -f /usr/share/zabbix-sql-scripts/postgresql/timescaledb/schema.sql"

- name: Ativar extensão TimescaleDB
  shell: sudo -u postgres psql -d {{ zabbix_db_name }} -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"
  notify: Restart PostgreSQL
