---
- name: Verificar se o pacote zabbix-release está instalado
  command: dpkg-query -W -f='${Status}' zabbix-release
  register: zabbix_release_status
  changed_when: false
  failed_when: zabbix_release_status.rc not in [0, 1]

- name: Adicionar repositório Zabbix
  block:
    - name: Baixar pacote do repositório Zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb
        mode: '0644'

    - name: Instalar repositório Zabbix
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Atualizar cache do APT
      apt:
        update_cache: yes
  when: "'install ok installed' not in zabbix_release_status.stdout"

- name: Instalar Zabbix Proxy com suporte a SQLite3
  apt:
    name: zabbix-proxy-sqlite3
    state: present
    update_cache: yes

- name: Garantir que o diretório /var/lib/zabbix exista com as permissões corretas
  file:
    path: /var/lib/zabbix
    state: directory
    owner: zabbix
    group: zabbix
    mode: '0755'

- name: Configurar DBName no zabbix_proxy.conf
  lineinfile:
    path: /etc/zabbix/zabbix_proxy.conf
    regexp: '^#?\s*DBName='
    line: 'DBName=/var/lib/zabbix/zabbix_proxy.db'
    create: yes
    backup: yes
  register: config_dbname

- name: Configurar Hostname no zabbix_proxy.conf
  lineinfile:
    path: /etc/zabbix/zabbix_proxy.conf
    regexp: '^#?\s*Hostname='
    line: "Hostname={{ inventory_hostname }}"
    create: yes
    backup: yes
  register: config_hostname

- name: Configurar Server no zabbix_proxy.conf
  lineinfile:
    path: /etc/zabbix/zabbix_proxy.conf
    regexp: '^#?\s*Server='
    line: "Server={{ zabbix_server_ip }}"
    create: yes
    backup: yes
  register: config_server

- name: Criar banco SQLite se não existir
  command: sudo -u zabbix /usr/sbin/zabbix_proxy -c /etc/zabbix/zabbix_proxy.conf -R config_cache_reload
  args:
    creates: /var/lib/zabbix/zabbix_proxy.db


- name: Habilitar e reiniciar Zabbix Proxy se necessário
  service:
    name: zabbix-proxy
    state: restarted
    enabled: yes
  when: config_dbname.changed or config_hostname.changed or config_server.changed or db_creation.changed
