---
- name: Instalar dependências básicas
  apt:
    name:
      - wget
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes

- name: Instalar psycopg2
  pip:
    name: psycopg2-binary

- name: Adicionar chave do PostgreSQL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Adicionar repositório do PostgreSQL
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Instalar PostgreSQL
  apt:
    name: "postgresql-16"
    state: present
    update_cache: yes