---
- name: Instalar dependências básicas
  apt:
    name:
      - wget
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes

- name: Instalar psycopg2
  pip:
    name: psycopg2-binary

- name: Adicionar chave do PostgreSQL
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Adicionar repositório do PostgreSQL
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present

- name: Instalar PostgreSQL
  apt:
    name: "postgresql-16"
    state: present
    update_cache: yes

- name: Permitir acesso ao banco Zabbix via md5
  lineinfile:
    path: /etc/postgresql/16/main/pg_hba.conf
    insertafter: EOF
    line: "host    {{ zabbix_db_name }}    {{ zabbix_db_user }}    0.0.0.0/0    md5"
    state: present

- name: Configurar postgresql.conf para aceitar conexões externas
  lineinfile:
    path: /etc/postgresql/16/main/postgresql.conf
    regexp: '^#?listen_addresses\s*='
    line: "listen_addresses = '*'"
    state: present
  notify: Restart PostgreSQL

- name: Adicionar repositório Zabbix e instalar pacote zabbix-sql-scripts
  block:
    - name: Baixar pacote do repositório Zabbix
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb
        mode: '0644'

    - name: Instalar repositório Zabbix
      ansible.builtin.apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Atualizar cache do APT após adicionar repositório Zabbix
      ansible.builtin.apt:
        update_cache: yes

    - name: Instalar zabbix-sql-scripts
      ansible.builtin.apt:
        name: zabbix-sql-scripts
        state: present