---
- name: Verificar se o pacote zabbix-release está instalado
  command: dpkg-query -W -f='${Status}' zabbix-release
  register: zabbix_release_status
  changed_when: false
  failed_when: zabbix_release_status.rc not in [0, 1]

- name: Adicionar repositório Zabbix
  block:
    - name: Baixar pacote do repositório Zabbix
      get_url:
        url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.0+ubuntu22.04_all.deb
        dest: /tmp/zabbix-release.deb
        mode: '0644'

    - name: Instalar repositório Zabbix
      apt:
        deb: /tmp/zabbix-release.deb
        state: present

    - name: Atualizar cache do APT
      apt:
        update_cache: yes
  when: "'install ok installed' not in zabbix_release_status.stdout"

- name: Instalar Zabbix Frontend e dependências PHP
  apt:
    name:
      - zabbix-frontend-php
      - zabbix-apache-conf
      - php8.1-pgsql
    state: present

- name: Criar zabbix.conf.php
  copy:
    dest: /etc/zabbix/web/zabbix.conf.php
    owner: www-data
    group: www-data
    mode: '0640'
    content: |
      <?php
      // Zabbix GUI configuration file.

      $DB['TYPE']                     = 'POSTGRESQL';
      $DB['SERVER']                   = '{{ zabbix_db_host }}';
      $DB['PORT']                     = '5432';
      $DB['DATABASE']                 = '{{ zabbix_db_name }}';
      $DB['USER']                     = '{{ zabbix_db_user }}';
      $DB['PASSWORD']                 = '{{ zabbix_db_password }}';

      $DB['SCHEMA']                   = '';

      $DB['ENCRYPTION']               = false;
      $DB['KEY_FILE']                 = '';
      $DB['CERT_FILE']                = '';
      $DB['CA_FILE']                  = '';
      $DB['VERIFY_HOST']              = false;
      $DB['CIPHER_LIST']              = '';

      $DB['VAULT']                    = '';
      $DB['VAULT_URL']                = '';
      $DB['VAULT_PREFIX']             = '';
      $DB['VAULT_DB_PATH']            = '';
      $DB['VAULT_TOKEN']              = '';
      $DB['VAULT_CERT_FILE']          = '';
      $DB['VAULT_KEY_FILE']           = '';

      $ZBX_SERVER_NAME                = 'Zabbix - LAB';
      $ZBX_SERVER                     = '{{ zabbix_server_ip }}';                                                                                                                                             │
      $ZBX_SERVER_PORT                = '10051';     

      $IMAGE_FORMAT_DEFAULT           = IMAGE_FORMAT_PNG;
      ?>
  notify: Restart Apache

- name: Ativar e iniciar Apache2
  service:
    name: apache2
    state: started
    enabled: yes
